---
title: "Exoplanet Data Visualizations"
author: "Ferris Esposito"
date: "May 21, 2019"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exoplanet Data Visualizations
Much can be learned about astronomical objects through data visualizations. Using datasets containing various information about exoplanets from **Nasa Exoplanet Archive** and **The Extrasolar Planets Encyclopedia**, I will illustrate various properties of exoplanets. 

```{r}
library(ggplot2)
library(colorRamps)
library(png)
```

```{r}
Exoplanet.Archive <- read.csv(file="composite_planet_data.csv")
Exoplanet.Catalog <- read.csv(file="exoplanet.eu_catalog.csv")
```

```{r}
img <- readPNG("star_field.png")
```

```{r}
ggplot(Exoplanet.Archive, aes(x=fst_logg, y=fst_lum)) + 
  
  geom_point(aes(color=fst_teff, size=fst_rad)) +
  
  scale_colour_gradientn(colors=rev(blue2red(200)), limits=c(3000,            8000), name="Effective Temperature (K)") +
  
  scale_size_continuous(range=c(0, 8), breaks=c(1, 5, 15, 30, 60), name=      "Stellar Radius [Solar radii]") +
 
  ylim(-3, 4) +
  
  labs(title="Stellar Luminosity v. Stellar Surface Gravity of Exoplanet Host Stars", x="Stellar Surface Gravity [log10(cm/s**2)]", 
  y="Stellar Luminosity [log10(Solar luminosity)]") +
  
  theme(plot.title=element_text(size=10))
```

```{r}
```